name:                proglang
version:             0.0.0.1

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6.2.1

library:
  source-dirs: src

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - proglang
      - hspec >= 2.7 && < 3
